interedit:
    NAME: interedit
    DATA_ROOT: ./data/interedit_processed
    MOTION_REP: global
    MODE: train
    CACHE: True

interedit_val:
    NAME: interedit
    DATA_ROOT: ./data/interedit_processed
    MOTION_REP: global
    MODE: val
    CACHE: True

interedit_test:
    NAME: interedit
    DATA_ROOT: ./data/interedit_processed
    MOTION_REP: global
    MODE: test
    CACHE: True
